reach/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('', include("website.urls"))
]

handler404 = 'website.views.error_404_view'

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [                         # List of allowable URLs that can be accessed for this particular app.
    path("", views.index, name="index"), # Route/url, and what view (and function there) that should be rendered when said route/URL is visited. 
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

website/urls.py
# Each app has its own URLs.py (made myself) to control what URLs are available for each particular app. 

from django.urls import path

from . import views

app_name = "website"
urlpatterns = [                         # List of allowable URLs that can be accessed for this particular app.
    path("", views.index, name="index"), # Route/url, and what view (and function there) that should be rendered when said route/URL is visited.
    path("homepage", views.homepage, name="homepage"),                                    # Giving a 'name' to a particular url pattern (path) makes it easier to reference later.
    path("login", views.user_login, name="login"),
    path("signup", views.signup, name="signup"),
    path("meditate", views.meditate, name="meditate"),
    path("resources", views.resources, name="resources"),
    path("aboutus", views.aboutus, name="aboutus"),
    path("error", views.error, name="error"),
    path("mood", views.mood, name="mood"),
    path("todaysmood", views.todaysmood, name="todaysmood"),
    path("moodlogs", views.moodlogs, name="moodlogs"),
    path("<int:user_id>/<int:mood_id>", views.moodedit, name="moodedit")  
]

website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
import datetime


# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures") #if airport is deleted from Airports, then flights referencing that airport also get deleted. If we have an airport we can access all of the "departures" from it.
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

class Passenger(models.Model):
    first = models.CharField(max_length=64)
    last = models.CharField(max_length=64)
    flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")
    # can use flights attribute to access all their flights, and if we have a flight we can use related_name "passengers" to see all the passengers.
    def __str__(self):
        return f"{self.first} {self.last}"

class Feeling(models.Model):
    feeling_options = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.feeling_options}"

class Sleep(models.Model):
    sleep_options = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.sleep_options}"

class Meals(models.Model):
    meals_options = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.meals_options}"

class Meetings(models.Model):
    meetings_options = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.meetings_options}"

class Mood(models.Model):
    username = models.CharField(max_length=64)
    date = models.DateTimeField(default=datetime.datetime.now())
    mood = models.ForeignKey(Feeling, on_delete=models.CASCADE, related_name="feeling")
    sleep = models.ForeignKey(Sleep, on_delete=models.CASCADE, related_name="sleep")
    meals = models.ForeignKey(Meals, on_delete=models.CASCADE, related_name="meals")
    meetings = models.ForeignKey(Meetings, on_delete=models.CASCADE, related_name="meetings")
    diary = models.TextField()



# class User(models.Model):
#     firstname = models.CharField(max_length=20)
#     lastname = models.CharField(max_length=20)
#     email = models.EmailField(max_length=30)
#     password = models.CharField(max_length=20)
#     country = models.CharField(max_length=20)

#     def __str__(self):
#         return f"{self.firstname} {self.lastname} is from {self.country}. His/her email is {self.email} and has the password {self.password}."

website/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse
from .models import Flight, Airport, Passenger, User, Mood, Feeling, Meetings, Meals, Sleep
import datetime 


class NewTaskForm(forms.Form):
    task = forms.CharField(label = "New Task") #widget=forms.TextInput(attrs={'class' : 'llabel'})

# Create your views here.
def index(request): #this index represents a view. When should we return this function/response? We do this in urls.py.
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("website:homepage"))

    return render(request, "website/landing.html") 

def homepage(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
            "message": "You have to log in to see this content!"
        })   
         
    return render(request, "website/homepage.html")

def user_login(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            print("we here.")
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("website:index")) #figure out what the URL for the index page in the website app is, and use that URL redirect to.
        else:
            return render(request, "website/login2.html", {
                "form": form
            })
    
    return render(request, "website/login2.html", {
        "form": NewTaskForm()
    })

def signup(request):
    if request.method == "POST":
        firstname = request.POST["firstname"] #get post data in the thing called 'username'
        lastname = request.POST["lastname"]
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        country = request.POST["country"]
        if (User.objects.filter(username=username).exists()):
            print("Sorry, username taken.")
            return render(request, "website/signup.html", {
                "message": "This username already exists!" 
            })
        
        user = User.objects.create_user(username=username, email=email, password=password, first_name=firstname, last_name=lastname)
        user1 = authenticate(request, username=username, password=password)
        if user1 is not None:
            login(request, user1)
            return HttpResponseRedirect(reverse("website:homepage"))

        else:
            return render(request, "website/signup.html", {
                "message": "Something went wrong." 
            })

    if request.user.is_authenticated:
        return render(request, "website/homepage.html", {
            "message": "You're already logged in, there's no need to sign up. If you want to make a new account, please log out first."
        })     
    return render(request, "website/signup.html")

def meditate(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
            "message": "You have to log in to see this content!"
        })
    return render(request, "website/meditate.html")

def mood(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
            "message": "You have to log in to see this content!"
        })

    return render(request, "website/newmood.html")

def todaysmood(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
            "message": "You have to log in to see this content!"
        })

    return render(request, "website/todaysmood.html", {
        "moods": Mood.objects.filter(username=request.user.username).last() 
    })  

def moodlogs(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
            "message": "You have to log in to see this content!"
        })

    if  'submitbutton' in request.POST:
        xmood = request.POST["mood"]
        print(xmood)
        xsleep = request.POST["sleep"]
        print(xsleep)
        xmeals = request.POST["meals"]
        print(xmeals)
        xpeople = request.POST["people"]
        print(xpeople)
        description = request.POST["description"]
        print(f"you, in a {xmood} mood, slept for {xsleep}, ate {xmeals}, met {xpeople}, and wrote: {description}")
        foo_instance = Mood.objects.create(username=request.user.username, date=datetime.datetime.now(), mood=Feeling.objects.get(id=xmood), sleep=Sleep.objects.get(id=xsleep), meals=Meals.objects.get(id=xmeals), meetings=Meetings.objects.get(id=xpeople), diary=description)
        #user = request.user.id 
        #print(Mood.objects.filter(username=request.user.username).last().id)
        print(f"you, in a {mood} mood, wrote: {description}")
        return render(request, "website/moodlogs.html", {
            "message": Mood.objects.filter(username=request.user.username).last(),
            "moods": Mood.objects.filter(username=request.user.username),
            "user_id": request.user.id,
            "first_name": request.user.first_name     
        })

    elif 'xbutton' in request.POST:
        value = request.POST["xbutton"]
        print(value)
        Mood.objects.filter(username=request.user.username, id=value).delete()
        return render(request, "website/moodlogs.html", {
            "message_two": Mood.objects.filter(username=request.user.username).last(),
            "moods": Mood.objects.filter(username=request.user.username),
            "user_id": request.user.id,
            "first_name": request.user.first_name    
        })        

    return render(request, "website/moodlogs.html", {
        "moods": Mood.objects.filter(username=request.user.username),
        "user_id": request.user.id,
        "first_name": request.user.first_name  
    }) 

def moodedit(request, user_id, mood_id):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
            "message": "You have to log in to see this content!"
        })

    entry = Mood.objects.filter(username=request.user.username).order_by('id')[mood_id]
    return render(request, "website/editentry.html", {
        "mood": entry 
    }) 

def resources(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {
            "message": "You have to log in to see this content!"
        })
    return render(request, "website/resources.html")

def aboutus(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))    
    return render(request, "website/aboutus.html")

def error(request):
    return render(request, "website/404.html", {
        "flights": Flight.objects.all(),
        "passengers": Passenger.objects.all() 
    })  

def error_404_view(request, exception):
    return render(request, 'website/404.html')  

website/templates/website/editentry.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'website/aboutus.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Entry</title>
    <link rel="icon" href="{% static 'website/pictures/logoPH.png' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lekton&display=swap" rel="stylesheet">
</head>
 
<body style="text-align: center; background-color: aliceblue;">
    <div class="bs-example">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a href="{% url 'website:homepage' %}" class="navbar-brand">
                <img src="{% static 'website/pictures/logoPH.png' %}" height="30" alt="REACH logo">
                REACH                
            </a>
           
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="justify-content-end collapse navbar-collapse" id="navbarCollapse" style="font-size: min(5vh, 20px);">
                <div class="navbar-nav">
                    <a href="{% url 'website:homepage' %}" class="nav-item nav-link">Home</a>
                    <a href="{% url 'website:meditate' %}" class="nav-item nav-link"> Meditate</a>
                    <a href="{% url 'website:moodlogs' %}" class="nav-item nav-link">Mood</a>
                    <a href="{% url 'website:resources' %}" class="nav-item nav-link">Resources</a>
                    <a href="{% url 'website:aboutus' %}" class="nav-item nav-link">About Us</a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link">Log Out</a>
                </div>
            </div>
        </nav>
    </div>
 
    <br><br><br><h1 style="font-family: 'Courier New', Courier, monospace; font-size: 37px;">Your entry made on {{ mood.date }}:</h1>
    <br>
    <ul style="list-style-position: inside; font-size: 25px;">
        <li style="color: black;">You were generally feeling {{ mood.mood }}</li>
        <li style="color: black;">Your diet entailed of {{ mood.meals }} meals</li>
        <li style="color: black;">Your social activity peaked at being with {{ mood.meetings }}</li>
        <li style="color: black;">You got {{ mood.sleep }} hours of sleep</li>
    </ul>
    <p style="font-size: 15px; color: darkorchid;"><i>Here's what you had to say about that day:</i></p>
    <div style="font-size: 24px; display: flex; display: inline-block;padding: 1rem 2rem; flex-direction: column; align-items: center; background-color: #fae9ed; border-radius: .5rem; text-align: center; color: grey;">
        {{ mood.diary }}
    </div> 
    <br>
    <div id="picture">
        <img src="{% static 'website/pictures/apples.png' %}" alt="Pic" width="700">
    </div>
</body>
</html>

website/templates/website/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <!-- MY STYLESHEET-->
    <link rel="stylesheet" href="../../static/website/styles3.css">
 
    <!-- Display NEED TO CHANGE-->
    <title>REACH - Home Page</title>
    <link rel="icon" href="../../static/website/pictures/logoPH.png">
 
    <!-- ANIMATE.STYLE LIB-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
 
    <!-- GOOGLE FONTS - HOPEFULLY RIGHT ONE?-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lekton&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="bs-example">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a href="{% url 'website:index' %}" class="navbar-brand">
                <img src="../../static/website/pictures/logoPH.png" height="30" alt="REACH logo">
            </a>
            REACH
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="justify-content-end collapse navbar-collapse" id="navbarCollapse" style="font-size: min(5vh, 20px);">
                <div class="navbar-nav">
                    <a href="{% url 'website:meditate' %}" class="nav-item nav-link"> Meditate</a>
                    <a href="{% url 'website:moodlogs' %}" class="nav-item nav-link">Mood</a>
                    <a href="{% url 'website:resources' %}" class="nav-item nav-link">Resources</a>
                    <a href="{% url 'website:aboutus' %}" class="nav-item nav-link">About Us</a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link">Log Out</a>
                </div>
            </div>
        </nav>
    </div>
    {% if message %}<br><br>
    <h1 style="font-size: 15px; color: rebeccapurple; text-align: center; padding-left: 5%; padding-right: 5%; background-color: orchid;">
        {{ message }}</h1>
    {% endif %}
    <p>
   <h1><b>Welcome to REACH!</b></h1 style="color: #AFDFDB;">  <br><br>
        <h4 style="color: rgb(32, 111, 148); font-size: 27px; padding-left: 7%; padding-right: 7%;">
    Welcome, {{ request.user.first_name|title }}.</h4><br><br>
    <h3 style="font-size: 20px; padding-left: 7%; padding-right: 7%;">
        If this is your first time here, congratulations on joining the team! Please use the navigation bar to get around our site. We would recommend starting with the 'Mood' tool, and then checking out the 'Meditation' tool; links for these can be seen in the top right!
        We hope you find value in the tools we provide, and that this site will be of use in these unique times.</h3>
    <img id="mainimg" src="../../static/website/pictures/high5.png" alt="" style="max-width: 720px;">
    </p>
 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/website/journal.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>Single Page</title>
  <style>
    div {
      display: none;
    }
  </style>

  <script>
    function showPage(page) {
      document.querySelectorAll('div').forEach(div => {
          div.style.display = 'none';
      })
      document.querySelector("#top").style.display = 'block';
      document.querySelector(`#${page}`).style.display = 'block'; // opposite of none
    }

    document.addEventListener('DOMContentLoaded', function() {
        document.querySelector("#top").style.display = 'block';
        document.querySelector("#picture").style.display = 'block';
        document.querySelectorAll('button').forEach(button => {
        button.onclick = function() {
          showPage(this.dataset.page);
        }
      })
    });

  </script>
</head>

<body style = "background-color: #f1e5f5; text-align: center;">
    <div id = "top" class="alert alert-info" role="alert">
        Kick back, relax, and enjoy your journal... &#x1F498;
    </div>
    <p></p>
    <button data-page="page1">Explanation</button>
    <button data-page="page2">Today's Entry</button>
    <button data-page="page3">History</button>
    <p></p>
    <div id="picture">
        <img src="sunset.jpeg" width="375" height="500" alt="Picture of my cat">
    </div>
    <div id="page1">
        <h1 class = "edgy1">Welcome to your journal. Record today's entry by clicking the "Today's entry" button.</h1>
    </div>
    <div id="page2">
        <h1 class = "edgy">What's on your mind?</h1>
        <form>
            <input class="input" id="entry" placeholder="Expunge your brain..." type="text" size="50">
            <input id="publish" placeholder = "Publish" type="submit">
        </form>
    </div>
    <div id="page3">
        <h1 class = "edgy1">Display all previous journal entries. Either through the database or list append feature (local storage on browser).</h1>
    </div>
</body>

</html>

website/templates/website/moodlogs.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'website/aboutus.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>All logs</title>
    <link rel="icon" href="{% static 'website/pictures/logoPH.png' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lekton&display=swap" rel="stylesheet">
    <script src="{% static 'website/moodlogs.js' %}"></script>
</head>
 
<body style="text-align: center; background-color: aliceblue;">
    <div class="bs-example">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a href="{% url 'website:homepage' %}" class="navbar-brand">
                <img src="{% static 'website/pictures/logoPH.png' %}" height="30" alt="REACH logo">
                REACH                
            </a>
           
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="justify-content-end collapse navbar-collapse" id="navbarCollapse" style="font-size: min(5vh, 20px);">
                <div class="navbar-nav">
                    <a href="{% url 'website:homepage' %}" class="nav-item nav-link">Home</a>
                    <a href="{% url 'website:meditate' %}" class="nav-item nav-link"> Meditate</a>
                    <a href="{% url 'website:resources' %}" class="nav-item nav-link">Resources</a>
                    <a href="{% url 'website:aboutus' %}" class="nav-item nav-link">About Us</a>
                    <a href="{% url 'users:logout' %}" class="nav-item nav-link">Log Out</a>
                </div>
            </div>
        </nav>
    </div>

    {% if message %}
    <div id = "top" class="alert alert-info" role="alert" style="font-family: 'Lekton', sans-serif; font-size: 18px;">
        Interesting to see you've been {{ message.mood }}. Your entry has been added below! &#x2728;
    </div>{% endif %}

    {% if message_two %}
    <div id = "top" class="alert alert-danger" role="alert" style="font-family: 'Lekton', sans-serif; font-size: 14px;">
        Entry has successfully been deleted! &#x2728;
    </div>{% endif %}
 
    <br><h1 style="font-family: 'Courier New', Courier, monospace; font-size: 50px;">{{ first_name|title }}, all of your logs are below.</h1><br>
    <h3 style="font-size: 15px;">Click on any of them to see more about them. You can also delete them by clicking the corresponding 'x' on the far right.</h3><br>
    <a href="{% url 'website:mood' %}">Make new diary entry</a><br><br>
    {% for mood in moods reversed %}
    <form action="{% url 'website:moodlogs' %}" method="post" style="justify-content: center;">
        {% csrf_token %}
        <button onclick="return confirm('Are you sure you want to delete this entry?')" 
         type="submit" name="xbutton" value="{{ mood.id }}" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </form>
    <div onclick="location.href = '{{ user_id }}/{{ forloop.revcounter0 }}'" id="logs" class="outfit{{ mood.mood }}" 
        style="display: flex; display: inline-block; padding: 1rem 2rem; flex-direction: column; align-items: center; border-radius: .5rem; text-align: center; color: grey;">
    Diary Entry <b>{{ forloop.revcounter }}</b>, made on {{ mood.date }}  Vibe: {{ mood.mood }}.</div><br><br>
    {% empty %}
    <div style="color: orangered;">You have yet to make any entries - click above to make one!</div>
    {% endfor %} 
    <br>
    <div id="picture">
        <img src="{% static 'website/pictures/404.png' %}" alt="Pic" width="700">
    </div>
</body>
</html>

<!-- <h2 style="font-size: 25px; padding-left: 10%; padding-right: 10%;" class = "padder">The logs should be above here.</h2> -->

website/templates/website/todaysmood.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'website/aboutus.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Today's Entry</title>
    <link rel="icon" href="{% static 'website/pictures/logoPH.png' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lekton&display=swap" rel="stylesheet">
</head>
 
<body style="text-align: center; background-color: aliceblue;">
    <div class="bs-example">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a href="{% url 'website:homepage' %}" class="navbar-brand">
                <img src="{% static 'website/pictures/logoPH.png' %}" height="30" alt="REACH logo">
                REACH                
            </a>
           
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="justify-content-end collapse navbar-collapse" id="navbarCollapse" style="font-size: min(5vh, 20px);">
                <div class="navbar-nav">
                    <a href="{% url 'website:homepage' %}" class="nav-item nav-link">Home</a>
                    <a href="{% url 'website:meditate' %}" class="nav-item nav-link"> Meditate</a>
                    <a href="{% url 'website:moodlogs' %}" class="nav-item nav-link">Mood</a>
                    <a href="{% url 'website:resources' %}" class="nav-item nav-link">Resources</a>
                    <a href="{% url 'website:aboutus' %}" class="nav-item nav-link">About Us</a>
                    <a href="{% url 'website:error' %}" class="nav-item nav-link">Log Out</a>
                </div>
            </div>
        </nav>
    </div>
 
    <br><br><br><h1 style="font-family: 'Courier New', Courier, monospace; font-size: 50px;">Your entry for {{ moods.date }}.</h1>
    <br>
    <h2 style="font-size: 25px; padding-left: 10%; padding-right: 10%;" class = "padder">You were feeling {{ moods.feeling }}, huh? Here's what you had to say: </h2>
    <div style="display: flex; display: inline-block;padding: 1rem 2rem; flex-direction: column; align-items: center; background-color: #fae9ed; border-radius: .5rem; text-align: center; color: grey;">
        {{ moods.diary }}
    </div> 
    <br>
    <div id="picture">
        <img src="{% static 'website/pictures/404.png' %}/" alt="Pic" width="700">
    </div>
</body>
</html>