reach/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('', include("website.urls"))
]

handler404 = 'website.views.error_404_view'

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [                         # List of allowable URLs that can be accessed for this particular app.
    path("", views.index, name="index"), # Route/url, and what view (and function there) that should be rendered when said route/URL is visited. 
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

website/urls.py
# Each app has its own URLs.py (made myself) to control what URLs are available for each particular app. 

from django.urls import path

from . import views

app_name = "website"
urlpatterns = [                         # List of allowable URLs that can be accessed for this particular app.
    path("", views.index, name="index"), # Route/url, and what view (and function there) that should be rendered when said route/URL is visited.
    path("homepage", views.homepage, name="homepage"),                                    # Giving a 'name' to a particular url pattern (path) makes it easier to reference later.
    path("login", views.user_login, name="login"),
    path("signup", views.signup, name="signup"),
    path("meditate", views.meditate, name="meditate"),
    path("resources", views.resources, name="resources"),
    path("aboutus", views.aboutus, name="aboutus"),
    path("error", views.error, name="error"),
    path("mood", views.mood, name="mood"),
    path("todaysmood", views.todaysmood, name="todaysmood"),
    path("moodlogs", views.moodlogs, name="moodlogs"),
    path("<int:user_id>/<int:mood_id>", views.moodedit, name="moodedit")  
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.contrib.auth import authenticate, login, logout 
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "website/homepage.html")
    
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"] #get post data in the thing called 'username'
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            print("caught")
            return HttpResponseRedirect(reverse("website:homepage"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid." 
            })    
    
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("website:homepage"))    
    return render(request, "users/login.html")

def logout_view(request):
    logout(request) 
    return render(request, "website/landing.html", {
        "message": "You have been succesfully logged out."
    })

def error_404_view(request, exception):
    return render(request, 'website/404.html') 

users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <!-- MY STYLESHEET-->
    <link rel="stylesheet" href="{% static 'website/login2.css' %}">

    <!-- Display NEED TO CHANGE-->
    <title>REACH - About Us</title>
    <link rel="icon" href="{% static 'website/pictures/logoPH.png' %}">

    <!-- ANIMATE.STYLE LIB-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

    <!-- GOOGLE FONTS - HOPEFULLY RIGHT ONE?-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lekton&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="bs-example">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <a href="{% url 'website:index' %}" class="navbar-brand">
                <img src="{% static 'website/pictures/logoPH.png' %}" height="30" alt="REACH logo">
                REACH                
            </a>
           
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="justify-content-end collapse navbar-collapse" id="navbarCollapse" style="font-size: min(5vh, 20px);">
                <div class="navbar-nav">
                </div>
            </div>
        </nav>
    </div>
    <div id="loginstuffs">
        <br>
        <h1 style="font-family: 'Courier New', Courier, monospace; font-size: 50px;">Welcome back!</h1>
        <br>
        <h2 style="font-size: 17px;">Enter your details below to sign in.</h2>
        <br>
        <h1 style="font-size: 25px; color: rebeccapurple;">{% if message %}
            <div>{{ message }}</div>
        {% endif %}</h1>
        <br>
        <form action="{% url 'users:login' %}" method="post">
        <div style="align-content: center;">
            {% csrf_token %}
            <!-- <label for="email" class="llabel">Email:&nbsp;&nbsp;</label>
            <input type="email" class="iinput" id="email" name="email" required><br>
            <label for="password" class="llabel">Password:&nbsp;&nbsp;</label>
            <input type="password" class="iinput" id="password" name="password" required><br><br> -->
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Password">
            <input type="submit" value="Login">
        </div>
            <!-- <br><br><button class="btn btn-primary" id = "submitbutton" type="submit">Log in!</button> -->
        </form>
        <div id="picture">
            <img src="{% static 'website/pictures/flyingmsg.png' %}" alt="Pic" width="500">
        </div>


    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

users/templates/users/user.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>User</title>
  </head>
  <body>
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username: {{ request.user.username }}</li>
    </ul>
    <a href="{% url 'users:logout' %}">Logout</a>
</body>
</html>